
#include "common.h"
#include "XLWStringUtil.h"
#include "option.h"

//英語の発音から日本語読みを強引に取得します。
static std::wstring EnglishOnsoToJapanese(const std::wstring& englishOnso,bool isrev)
{
	//AH0 とか AO2 とかそういうのをすべて統一します.
	const WCHAR * replaceTablePlain[] = {
	 L"0",L""
	,L"1",L""
	,L"2",L""
	,NULL,NULL};

	std::wstring w =L"   " + XLWStringUtil::replace(englishOnso, replaceTablePlain,false) +L" ";
	const WCHAR * replaceTabl0[] = {
	  L"   M AH",L" ま"
	 ,L"   K IH",L" き"
	 ,L"   AA N",L" おん"
	 ,NULL,NULL
	};
	w = XLWStringUtil::replace(w, replaceTabl0,isrev);

	const WCHAR * replaceTabl1[] = {
	 L" S T ER",L" すたー"
	,L" B R AH",L" ぶら"
	,L" B R AH",L" ぶら"
	,L" L OW ER",L" ろーらー"
	,L" S T AA R",L" すたー"
	,L" EY B R AH",L" あぶら"
	,L" L T IY",L" てぃ"
	,L" NG L IY",L" んぐりー"
	,L" M AH T",L" めいと"
	,L" M EY T",L" めいと"
	,L" T IH NG",L" しんぐ"
	,L" HH AE M",L" はむ"
	,L" N S AH L",L" んせる"
	,L" S AH L",L" せーる"
	,L" W IH L S AH N",L" うぃるそん"
	,L" S AH N",L" せん"
	,L" R AY AH",L"らいあ"
	,L" AA T IY",L" あーりー"
	,L" G Y UW",L" ぎゅー"
	,L" D IH S",L" でぃす"
	,L" D IH Z AY",L" でざい"
	,L" D IH V EH",L" でべ"
	,L" L AH P ER",L" ろっぱー"
	,L" EH R IH",L" あり"
	,L" SH AH L",L" しゃる"
	,L" D AW N",L" だうん"
	,L" Y AA HH",L" や"
	,L" JH UW AH",L" じゅえ"
	,L" T AW N",L" たうん"
	,L" CH AE N AH",L"ちゃんね"
	,L" B R AW Z ER",L" ぶらうざ"
	,L" AA R IH",L" あーり"
	,L" M AH N",L" まん"
	,L" N AH L",L" なる"
	,L" S EH N",L" せん"
	,L" S K UW L",L" すくーる"
	,L" K UW L",L" くーる"
	,L" Y AA R",L" やー"
	,L" K R AE",L" くら"
	,L" G R AE",L" ぐら"
	,L" SH EH R",L" しぇあ"
	,L" R EH S",L" れす"
	,L" F AO R",L" ふぉー"
	,L" R EH JH IH",L" れじ"
//	,L" R EH JH",L" らっじ"
	,L" R EH TH",L" らーど"
	,L" R IH K",L" りっく"
	,L" R IH JH",L" れーじ"
	,L" R IH CH",L" りっち"
	,L" N AO R",L" なー"
	,L" P IH CH",L" ぴっち"
	,L" K W AH",L" こー"
	,L" W IH P",L" ういっぷ"
	,L" K AH M AE",L" こま"
	,L" K AH M",L" こん"
	,L" P Y UW",L" ぴゅー"
	,L" S IH NG",L" しん"
	,L" G AH L",L" ぐる"
	,L" K W OW",L" くぉー"
	,L" B AE K",L" ばっく"
	,L" L AY T",L" らいと"
	,L" L AY Z",L" らいず"
	,L" L AY K",L" らいく"
	,L" B AH L",L" ぶる"
	,L" AH L ER",L" ありー"
	,L" S EH L",L" せる"
	,L" B L AE",L" ぶらっ"
	,L" B L AO",L" ぶろー"
	,L" S L IY",L" すりー"
	,L" P L IY",L" ぷりー"
	,L" F L IY",L" ふりー"
	,L" L AH S",L" れす"
	,L" K AH L",L" かる"
	,L" M AY K AH L",L" まいける"
	,L" W AO K ER",L" うぉーかー"
	,L" W AO K",L" うぉーく"
	,L" K IH NG",L" きんぐ"
	,L" K ER Z",L" かーず"
	,L" S L AY",L" すらい"
	,L" D IH NG Z",L" でぃんぐず"
	,L" D IH NG",L" でぃんぐ"
	,L" G ER IH NG",L" がーりんぐ"
	,L" T ER IH NG",L" とりんぐ"
	,L" ER IH NG",L" りんぐ"
	,L" D AH L",L" でる"
	,L" R IY AH",L" りあー"
	,L" N UW Z",L" ニュース"
	,L" R IH NG K",L" りんく"
	,L" IH NG K",L" いんぐ"
	,L" M Y UW",L" みゅー"
	,L" Z IH K",L" じっく"
	,L" S P AA",L" すぱ"
	,L" D AH N S IY",L" でんしー"
	,L" T AH N IY",L" てぃにー"
	,L" T R OY",L" とろい"
	,L" L UW AH",L" るあー"
	,L" L EH K S",L" れっくす"
	,L" EH V ER",L" えばー"
	,L" G R IY N",L" ぐりーん"
	,L" R IY N",L" りーん"
	,L" R AE S",L" らす"
	,L" SH AH N Z",L" しょんず"
	,L" SH AH N",L" しょん"
	,L" T IH V",L" てぃぶ"
	,L" D AW G",L" どっぐ"
	,L" B ER D",L" ばーど"
	,L" L EY S",L" れーす"
	,L" L EY N",L" れーん"
	,L" L EY T",L" れーと"
	,L" L EY M",L" らむ"
	,L" P AE M",L" ぱむ"
	,L" B AE K",L" ばっく"
	,L" OW K EY",L" おーけー"
	,L" S ER CH",L" さーち"
	,L" K T ER",L" くたー"
	,L" S T ER",L" すたー"
	,L" S T R AO",L" すとろ"
	,L" AE B S AH",L" あぶそ"
	,L" L UW T",L" りゅーと"
	,L" OW V ER",L" おーばー"
	,L" P AW ER",L" ぱわー"
	,L" T R IY",L" とぅりー"
	,L" B AE NG K",L" ばんく"
	,L" S IH T IY",L" してぃ"
	,L" B OW L",L" ぼーる"
	,L" F AE N",L" ふぁん"
	,L" HH Y UW",L" ひゅう"
	,L" T R AH",L" とら"
	,L" S T AA R",L" すたー"
	,L" S AH JH",L" せーじ"
	,L" EY SH AH N",L" せーしょん"
	,L" D Y ER",L" でぃ"
	,L" L AY V",L" らいぶ"
	,L" F AY ER",L" ふぁいあ"
	,L" W EH R",L" うぇあ"
	,L" W ER K",L" わーく"
	,L" M EY SH AH N",L" めーしょん"
	,L" P AA R T S",L" ぱーつ"
	,L" T AH M AA",L" とぅも"
	,L" P EH R",L" ぺあー"
	,L" P AA R",L" ぱー"
	,L" Z AY N",L" ざいん"
	,L" M IH NG",L" みんぐ"
	,L" W IH CH",L" いっち"
	,L" T AH M",L" てむ"
	,L" K OW P",L" こーぷ"
	,L" L T IY",L" てぃ"
	,L" R ER Z",L" やーど"
	,L" G Y UW",L" ぎゅー"
	,L" EH R IH",L" あり"
	,L" DH ER",L" ざー"
	,L" N D ER",L" んだー"
	,L" K S AH",L" くす"
	,L" K AH N EH",L" こね"
	,L" K AH N",L" こっん"
	,L" K AW N T ER",L" かうんたー"
	,L" K AW N T",L" かうんと"
	,L" B R AW N",L" ぶらうん"
	,L" B R AW",L" ぶろー"
	,L" B R OW",L" ぶろー"
	,L" P ER",L" ぱー"
	,L" T IH NG",L" てぃんぐ"
	,L" V AY AH",L" ばいお"
	,L" L IH T",L" れっと"
	,L" W UH D",L" うっど"
	,L" F OW N",L" ふぉん"
	,L" N IH K",L" にっく"
	,L" B AY T",L" ばいと"
	,L" K Y OW",L" きょ"
	,L" AY T AH M",L" あいてむ"
	,L" W AY T",L" ほわいと"
	,L" HH W AY T",L" ほわいと"
	,L" W AY N",L" うぃん"
	,L" P AH L",L" ぷる"
	,L" L EY B AH",L" らべ"
	,L" P ER S IH",L" ぱーそ"
	,L" N IH L",L" なる"
	,L" M AY K R OW",L" まいくろ"
	,L" M AY K R OW",L" まいくろ"
	,L" K OW D",L" こーど"
	,L" N IH K",L" にっく"
	,L" M IH D AH",L" みど"
	,L" M IH D",L" みっど"
	,L" N AY T",L" ないと"
	,L" M IH S",L" みす"
	,L" D AH N",L" どん"
	,L" D AH B AH",L" だぶ"
	,L" K L OW",L"くろー"
	,L" D R IH",L" どり"
	,L" M EY N",L" めいん"
	,L" M AO R",L" もー"
	,L" K Y AH",L" きゅ"
	,L" T AO R",L" とあー"
	,L" T AO L",L" とーる"
	,L" T AH N T",L" たんと"
	,L" JH IH K AH",L" じか"
	,L" JH IH K",L" じっく"
	,L" JH IH N",L" じん"
	,L" K OY N",L" こいん"
	,L" L AH V",L" らぶ"
	,L" P AE N",L" ぱん"
	,L" AO T AH",L" おーと"
	,L" AO T AA",L" おーと"
	,L" AO T OW",L" おーと"
	,L" AO T AH",L" おーと"
	,L" B IY L",L" びる"
	,L" B IY L",L" びる"
	,L" CH AE M",L" ちゃん"
	,L" AE L AH",L"あら"
	,L" CH EY M",L"ちぇん"
	,L" M EY SH AH N",L" めーしょん"
	,L" SH AH N",L" しょん"
	,L" L EH V AH L",L" れべる"
	,L" V AH L",L" びる"
	,L" P R OW",L"ぷろ"
	,L" V AH S",L" ばす"
	,L" W AO R P",L" わーぷ"
	,L" W AO R",L" うぉー"
	,L" W AA SH",L" うぁっしゅ"
	,L" S EH V AH",L" せぶ"
	,L" B R EH",L" ぶら"
	,L" M AE K",L" まっく"
	,L" M AE D",L" まっど"
	,L" M AO D",L" もっど"
	,L" Y AH L EY",L" れー"
	,L" T AH CH",L" たっち"
	,L" T R AE N Z",L" とらんす"
	,L" S AH B",L" さぶ"
	,L" L IH NG",L" りん"
	,L" CH AE T",L" ちゃっと"
	,L" S IH M",L" しん"
	,L" W EY T",L" うぇいと"
	,L" T AH L",L" とる"
	,L" T IY N",L" てぃーん"
	,L" T ER IY",L" とりー"
	,L" F AH NG K",L" ふぁんく"
	,L" CH AY N AH",L" ちゃいな"
	,L" L K AH HH AA",L" るこー"
	,L" K AA R",L" かー"
	,L" K AH P",L" かっぷ"
	,L" K EY K",L" けーき"
	,L" F IY N",L" ふぇいん"
	,L" AO R D ER",L" おーだー"
	,L" AY D AH",L" あいど"
	,L" K Y UW",L" きゅー"
	,L" K AH T",L" かっと"
	,L" P AH S",L" ぷす"
	,L" K AA M",L" こん"
	,L" EH N EY",L" いねー"
	,L" AE M AH",L" あま"
	,L" Z AA N",L" ぞん"
	,L" T AY M",L" たいむ"
	,L" B AA D IY",L" ぼてぃ"
	,L" K OW L",L" こーる"
	,L" S EH S",L" せす"
	,L" B AY OW",L" ばいお"
	,L" HH AE P IY",L" はっぴー"
	,L" M AY Z",L" まいず"
	,L" N D AH M",L" んだむ"
	,L" D AH M",L" だん"
	,L" D AH S",L" だす"
	,L" B AE D",L" ばっど"
	,L" F Y UW",L" ふゅー"
	,L" B AO L",L" ぼる"
	,L" B AO R",L" ぼー"
	,L" R AH N",L" らん"
	,L" P IH NG K",L" ぴんく"
	,L" P L EY",L" ぷれい"
	,L" JH AE P",L" じゃっぷ"
	,L" JH AH1 M",L" じゃん"
	,L" M AH N IY",L" まねー"
	,L" M EY K IH NG",L" めいきんぐ"
	,L" T R AE",L" とらっ"
	,L" K UH R AH",L" くら"
	,L" D AE N",L" だ"
	,L" JH AA V AH",L" じゃば"
	,L" F L AW ER",L" ふらわー"
	,L" N AE S AH",L" なさ"
	,L" M EY D",L" めいど"
	,L" HH AH T",L" はっと"
	,L" L OW S",L" ろーず"
	,L" L IH R",L" りあー"
	,L" M AW S",L" まうす"
	,L" N D IY",L" んでぃ"
	,L" B IH R",L" びあー"
	,L" HH AA R",L" はー"
	,L" HH IY TH",L" はーと"
	,L" D IH L IY",L" でりー"
	,L" S AY",L" さい"
	,L" S AY Z",L" さいず"
	,L" T AE K S IY",L" たくしー"
	,L" T IY",L" てぃー"
	,L" SH AO R",L" しょー"
	,L" L UH K",L" るっく"
	,L" W AH JH",L" げーじ"
	,L" D AO G",L" どっぐ"
	,L" T EH K",L" てき"
	,L" L OW G OW",L" ろご"
	,L" S AO R",L" そー"
	,L" K OW D ER",L" こーだー"
	,L" M IH K",L" みっく"
	,L" M OW B AH L",L" もばいる"
	,L" N UW D AH L",L" ぬーどる"
	,L" K L AH B",L" くらぶ"
	,L" K L AH",L" これー"
	,L" K AY N",L" かいん"
	,L" B AH S",L" ばす"
	,L" SH AH N AH L",L" しょなる"
	,L" IH NG G",L" いんぐ"
	,L" HH ER AA",L" はら"
	,L" G AH N",L" ごん"
	,L" D AA R",L" だー"
	,L" R OW M AE",L" ろま"
	,L" M AE CH",L" まっち"
	,L" M AH T IH",L" まて"
	,L" R IY AH L",L" りある"
	,L" V IH1 N IY",L" べにー"
	,L" B AY B AH",L" ばいぶ"
	,L" F IH SH",L" ふぃっしゅ"
	,L" S T AH",L" すたっ"
	,L" T OW N IY",L" とに"
	,L" N IY AH",L" にあ"
	,L" G R EH",L" ぐれっ"
	,L" S W IY",L" すいー"
	,L" K Y ER IY",L" きゅりー"
	,L" P EH R AH",L" ぱら"
	,L" R AH N",L" れん"
	,L" JH AO R",L" じょー"
	,L" D AA L",L" どーる"
	,L" JH EY M",L" じぇいむ"
	,L" T IH L AH",L" てぃら"
	,L" L AH N",L" らん"
	,L" L AW D",L" らうど"
	,L" HH EH R AH",L" はろ"
	,L" S T EY",L" すてー"
	,L" F IH T",L" ふぇっと"
	,L" M AA R K OW",L" まるこ"
	,L" M AA R IY",L" まり"
	,L" T R IH",L" とりっ"
	,L" W UH M AH",L" うーま"
	,NULL,NULL};
	w = XLWStringUtil::replace(w, replaceTabl1,isrev);

	const WCHAR * replaceTabl2[] = {
	 L" W UH",L" うっ"
	,L" G AA",L" ごっ"
	,L" V IH",L" び"
	,L" CH OY",L" ちょい"
	,L" P OY",L" ぽい"
	,L" P IH",L" ぴ"
	,L" L AO",L" ろー"
	,L" L OY",L" ろい"
	,L" HH EH",L" へっ"
	,L" K EH",L" け"
	,L" NG K",L" んく"
	,L" HH ER",L" はー"
	,L" HH IY",L" ひー"
	,L" ER TH",L" あーす"
	,L" HH AO",L" ふぉ"
	,L" CH IH",L" ちっ"
	,L" B EH",L" べ"
	,L" IY T",L" いーと"
	,L" F ER",L" ふぁ"
	,L" JH UW",L" じゅ"
	,L" IH M",L" えん"
	,L" B EH",L" べっ"
	,L" IH NG",L" ん"
	,L" F AO",L" ふぁ"
	,L" L IH",L" りっ" 
	,L" R UW",L" るー"
	,L" AW T",L" あうと"
	,L" W AY",L" わい"
	,L" EH G",L" えっぐ"
	,L" CH IY",L" っち"
	,L" V AH",L" ぶ"
	,L" S IY",L" しー"
	,L" S EH",L" せっ"
	,L" SH AE",L" しゃ"
	,L" D OW",L" どー"
	,L" AO R",L" あー"
	,L" JH OY",L" じょい"
	,L" JH AA",L" じゃ"
	,L" HH IH",L" ひー"
	,L" K ER",L" かー"
	,L" D EY",L" でー"
	,L" M OW",L" もー"
	,L" F EY",L" ふぇ"
	,L" JH AH",L" じゃ"
	,L" T AH",L" とぅ"
	,L" F IY",L" ふぃー"
	,L" K AO",L" こー"
	,L" T UW",L" とぅ"
	,L" W AH",L" うぉ"
	,L" W OW",L" うぉ"
	,L" W AH",L" わ"
	,L" R IH",L" り"
	,L" M AE",L" ま"
	,L" M AH",L" ま"
	,L" P EY",L" ぺー"
	,L" HH AE F",L" はーふ"
	,L" HH AE K",L" はっく"
	,L" HH AE",L" は"
	,L" HH EH",L" へ"
	,L" CH AE",L" ちゃ"
	,L" CH AO",L" ちょ"
	,L" M AH",L" め"
	,L" M EH",L" め"
	,L" D AA",L" ど"
	,L" D AO",L" ど"
	,L" D AA",L" ど"
	,L" G UW",L" ぐー"
	,L" M AH",L" みっ"
	,L" K IY",L" きー"
	,L" K AH",L" か"
	,L" D UW",L" どぅ"
	,L" D OW",L" ど"
	,L" N IY",L" にー"
	,L" L EY",L" れ"
	,L" S AO",L" そ"
	,L" G IH",L" ぎ"
	,L" G AH",L" が"
	,L" T EH",L" て"
	,L" T EH",L" て"
	,L" L AH",L" れ"
	,L" B AE",L" ば"
	,L" F AH",L" ふぃ"
	,L" HH AH",L" へ"
	,L" P AW",L" ぷぁ"
	,L" F AW",L" ふぁう"
	,L" P AA",L" ぱ"
	,L" T OW",L" とー"
	,L" R AW",L" らう"
	,L" P ER",L" ぺー"
	,L" P EH",L" ぺ"
	,L" HH OW",L" ほ"
	,L" F IY",L" ふぃー"
	,L" K OW",L" こー"
	,L" L AY",L" らい"
	,L" AH P",L" あっぷ"
	,L" T EY",L" てー"
	,L" IH K",L" えく"
	,L" AH L",L" うる"
	,L" S IY",L" しー"
	,L" T OY",L" とーい"
	,L" T AE",L" たっ"
	,L" F AE",L" ふぁ"
	,L" B OW",L" ぼー"
	,L" M AE",L" ま"
	,L" N IH",L" に"
	,L" AW ER",L" わー"
	,L" K AE",L" きゃ"
	,L" K EY",L" けー"
	,L" L UW",L" りゅー"
	,L" AO F",L" おふ"
	,L" OY L",L" おいる"
	,L" M EH",L" めっ"
	,L" B IY",L" びー"
	,L" N IH",L" にっ"
	,L" K IH",L" きっ"
	,L" B AE",L" ばっ"
	,L" P AE",L" ぱ"
	,L" L IY",L" りー"
	,L" S EH",L" せ"
	,L" B ER",L" ばー"
	,L" D AW",L" どっ"
	,L" N EY",L" ねー"
	,L" S IH",L" し"
	,L" V ER",L" ばー"
	,L" Z EH",L" ぜ"
	,L" L AO",L" ろ"
	,L" R OY",L" ろい"
	,L" L EH",L" れ"
	,L" N UW",L" にゅー"
	,L" R IY",L" りー"
	,L" T AY",L" てぃ"
	,L" D IY",L" でぃ"
	,L" B IH",L" びっ"
	,L" B AH",L" ばっ"
	,L" AE L",L" あー"
	,L" R AY",L" らい"
	,L" T UH",L" とぅ"
	,L" T IY",L" てぃ"
	,L" L AE",L" ら"
	,L" V IY",L" びぃ"
	,L" R OW",L" ろー"
	,L" T EY",L" てー"
	,L" T ER",L" たー"
	,L" L AY",L" らい"
	,L" B AE",L" ばっ"
	,L" AE M",L" あん"
	,L" AH N",L" あん"
	,L" AA N",L" あん"
	,L" S AE",L" さ"
	,L" P ER",L" ぱー"
	,L" B UH",L" ぶっ"
	,L" R UH",L" ろっ"
	,L" Y UH",L" ろぉ"
	,L" P UH",L" ぷっ"
	,L" T UH",L" とぅ"
	,L" CH UH",L" ちっ"
	,L" N UH",L" ぬっ"
	,L" M UH",L" むっ"
	,L" HH UH",L" はっ"
	,L" S UH",L" しっ"
	,L" K UH",L" くっ"
	,L" D UH",L" どぅ"
	,L" F UH",L" ふっ"
	,L" SH UH",L" しっ"
	,L" Z UH",L" ずっ"
	,L" L UH",L" ろっ"
	,L" G UH",L" ぐっ"
	,L" SH AA",L" しゃー"
	,L" D AA",L" どっ"
	,L" T AA",L" と"
	,L" V AA",L" ぶぁ"
	,L" HH AA",L" はぁ"
	,L" HH IH",L" はい"
	,L" HH OW",L" ほー"
	,L" K AA",L" こー"
	,L" S AA",L" すっ"
	,L" L AA",L" ろっ"
	,L" M AA",L" まー"
	,L" R OW",L" あろー"
	,L" ER OW",L" えあろ"
	,L" B IH",L" びっ"
	,L" D AE",L" だっ"
	,L" AH D",L" あど"
	,L" M IH",L" みい"
	,L" AE D",L" あーど"
	,L" AE D",L" あーど"
	,L" AE D",L" あど"
	,L" AH L",L" らる"
	,L" AH N",L" あん"
	,L" AE N",L" あん"
	,L" M AY",L" まい"
	,L" R ER",L" やー"
	,L" IH NG",L" いんぐ"
	,L" Z IH",L" じー"
	,L" L IY",L" りー"
	,L" JH EH",L" じぇ"
	,L" V IH",L" ぶー"
	,L" L AH",L" ぷ"
	,L" M AH",L" め"
	,L" SH AH",L" しょ"
	,L" S AH",L" すっ"
	,L" R AH",L" ろー"
	,L" R EH",L" れ"
	,L" R EH",L" れ"
	,L" R AA",L" ろ"
	,L" R IH",L" り"
	,L" V ER",L" ばー"
	,L" EY P",L" あぷっ"
	,L" AE P",L" あぷっ"
	,L" P OW",L" ぽーす"
	,L" F AA",L" ふぉっ"
	,L" HH OW",L" ほー"
	,L" F AY",L" ふぁい"
	,L" S AW",L" さう"
	,L" N D",L" んど"
	,L" L Z",L" るず"
	,L" S OW",L" そー"
	,L" AE P",L" あぷ"
	,L" AA R",L" あー"
	,L" ER IH",L" あり"
	,L" M ER",L" まー"
	,L" M Z",L" むず"
	,L" ER EY",L" あれい"
	,L" G AA",L" ご"
	,L" R IH",L" りっ"
	,L" T IY",L" とりー"
	,L" B IY",L" びー"
	,L" AE S",L" あす"
	,L" AA S",L" あす"
	,L" K AE",L" きゃっ"
	,L" T ER",L" たー"
	,L" K S",L" くす"
	,L" T EH",L" て"
	,L" T AY",L" てぃ"
	,L" K UW",L" くー"
	,L" T IY",L" てぃー"
	,L" CH ER",L" ちゃー"
	,L" T AY",L" たい"
	,L" W ER",L" わー"
	,L" SH OW",L" しょう"
	,L" SH AA",L" しょっ"
	,L" SH OW",L" しょお"
	,L" T IH",L" てぃ"
	,L" T EH",L" て"
	,L" K R AE",L" くら"
	,L" K R AO",L" くろ"
	,L" G R AE",L" ぐら"
	,L" W AY",L" ほわ"
	,L" HH UW",L" ふー"
	,L" EH R",L" えあー"
	,L" L AO",L" ろっ"
	,L" P AO R",L" ぽー"
	,L" SH EH",L" しぇ"
	,L" SH IH",L" しっ"
	,L" P EY",L" ぺー"
	,L" P IY",L" ぴー"
	,L" R AY",L" らい"
	,L" R IH",L" りっ"
	,L" T AY",L" たい"
	,L" R AE",L" ら"
	,L" S EY",L" せー"
	,L" W EY",L" うぇー"
	,L" W IH",L" うい"
	,L" DH IY",L" でぃ"
	,L" F AO R",L" ふぉー"
	,L" D IY",L" でぃ"
	,L" M EY",L" めー"
	,L" JH EH",L" じぇ"
	,L" D ER",L" だー"
	,L" L IY",L" りぃ"
	,L" D IH",L" でぃ"
	,L" D AA",L" だ"
	,L" IH L",L" える"
	,L" EH L",L" える"
	,L" D AO",L" ど"
	,L" R AH",L" らー"
	,L" EH L",L" える"
	,L" ER AA",L" らー"
	,L" R OW",L" ろー"
	,L" D OW",L" どー"
	,L" R IY",L" りー"
	,L" D AH",L" だー"
	,L" D EH",L" で"
	,L" W IH",L" うぃ"
	,L" N ER",L" なー"
	,L" L EH",L" れ"
	,L" K T",L" くと"
	,L" K EY",L" けー"
	,L" F IH",L" ふぃー"
	,L" T W",L" とぅ"
	,L" M IY",L" みぃ"
	,L" M IH",L" みぃ"
	,L" S EH",L" さー"
	,L" R IY",L" りー"
	,L" M IH",L" みっ"
	,L" K AH",L" か"
	,L" L ER",L" らー"
	,L" M IY",L" みー"
	,L" NG ER",L" んがー"
	,L" IH NG",L" いんぐ"
	,L" IH CH",L" ぴっち"
	,L" F AY",L" ふぁ"
	,L" Z AY",L" ざい"
	,L" P AH",L" ぷ"
	,L" R AH",L" ろ"
	,L" L AH",L" ろ"
	,L" W AH",L" くー"
	,L" S ER",L" さー"
	,L" L AE",L" ら"
	,L" V IH",L" びぃ"
	,L" L LY",L" りー"
	,L" K ER",L" かー"
	,L" R IH",L" り"
	,L" S UW",L" すー"
	,L" G ER",L" がー"
	,L" N AY",L"ない"
	,L" HH AY",L" はい"
	,L" V IH",L" び"
	,L" T UW",L" とぅー"
	,L" Z IH",L" じっ"
	,L" Y EH",L" いえ"
	,L" L OW",L" ろー"
	,L" R IY",L" りー"
	,L" B EY",L" べー"
	,L" N OW",L" のー"
	,L" OW L",L" おーる"
	,L" AA N",L" おん"
	,L" AO N",L" おん"
	,L" S ER",L" さー"
	,L" S IY",L" しー"
	,L" R EY",L" れー"
	,L" IH M",L" いん"
	,L" IH N",L" いん"
	,L" D EH",L" でっ"
	,L" F IY",L" ふぃー"
	,L" N EH",L" ねっ"
	,L" W AO",L" うぉー"
	,L" R AH",L" ろ"
	,L" G EY",L" げー"
	,L" V AH",L" べ"
	,L" CH EY",L" ちぇ"
	,L" V EY",L" べ"
	,L" G AH",L" が"
	,L" Z ER",L" ざー"
	,L" HH AW",L" はう"
	,L" DH ER",L" ざー"
	,L" F AH",L" ふぇー"
	,L" S AA",L" そ"
	,L" G OW",L" ごー"
	,L" AY S",L" あいす"
	,L" B AA",L" ぼっ"
	,L" B OY",L" ぼーい"
	,L" F EY",L" ふぇぃ"
	,L" AE F",L" あふ"
	,NULL,NULL};
	w = XLWStringUtil::replace(w, replaceTabl2,isrev);

	const WCHAR * replaceTable3[] = {
	 L" ZH",L" ず"
	,L" AH",L" あ"
	,L" AW",L" ぁ"
	,L" AA",L" あー"
	,L" AE",L" あー"
	,L" EH",L" え"
	,L" ER",L" えあ"
	,L" EY",L" えい"
	,L" NG",L" んぐ"
	,L" IH",L" え"
	,L" IY",L" い"
	,L" CH",L" ち"
	,L" JH",L" じ"
	,L" AY",L" あい"
	,L" OW",L" おー"
	,L" EH",L" い"
	,L" SH",L" しゅ"
	,L" AO",L" おー"
	,L" UW",L" うー"
	,L" TH",L" す"
	,L" B",L" ぶ"
	,L" D",L" ど"
	,L" F",L" ふ"
	,L" G",L" ぐ"
	,L" K",L" く"
	,L" L",L" る"
	,L" M",L" む"
	,L" N",L" ん"
	,L" P",L" ぷ"
	,L" R",L" あ"
	,L" S",L" す"
	,L" T",L" と"
	,L" V",L" ぶ"
	,L" W",L" う"
	,L" Y",L" い"
	,L" Z",L" ず"
	,NULL,NULL};
	w = XLWStringUtil::replace(w, replaceTable3,isrev);

	w = XLWStringUtil::replace(w,L" ",L"");
	return w;
}

static void ReadAllForYomi(FILE * fp)
{
	const char* p;
	std::vector<char> buferVec(65535);
	char* buffer = &buferVec[0];

	while(!feof(fp))
	{
		if ( fgets(buffer,buferVec.size() - 1,fp) == NULL) break;
//		if ( buf[0] == ';' )
//		{//コメント
//			continue;
//		}
		if (! isalpha(buffer[0]) )
		{//先頭が英語ではないものは全て無視
			continue;
		}
		//タイトルの終端を探す.
		for(p = buffer ; *p ; p++ )
		{
			if (!isalpha(*p))
			{
				break;
			}
		}
		if (*p != ' ')
		{//タイトルではない、または、 (1)などの別名が有るパティーン。容赦なく無視.
			continue;
		}
		const char* titleend = p;
		
		//発音が始まるまでスキップします
		for(p ; *p ; p++ )
		{
			if (isalpha(*p))
			{
				break;
			}
		}
		if (!isalpha(*p))
		{//読みがない.
			continue;
		}
		const std::string title = std::string(buffer,0,(int) (titleend - buffer) );
		const std::wstring titleW = _U2W(title);
		const std::wstring hatsuonW = XLWStringUtil::chop( _U2W(p) );
		std::wstring yomiW = EnglishOnsoToJapanese(hatsuonW,false);
		
		//結果の表示.
		if ( Option::m()->getShow() == Option::TypeShow_NoEmpty)
		{//空ならば表示しない?
			if (yomiW.empty())
			{
				continue;
			}
		}
		else if ( Option::m()->getShow() == Option::TypeShow_Empty)
		{//空なものだけ表示する
			if (!yomiW.empty())
			{
				continue;
			}
		}

		switch ( Option::m()->getCase())
		{
		case Option::TypeCase_None:	break;
		case Option::TypeCase_Kata:	yomiW = XLWStringUtil::mb_convert_kana(yomiW,L"KC"); break;
		case Option::TypeCase_Kana:	break;
		}
	
		wprintf(L"%ls	@%ls	%ls\n",yomiW.c_str(),titleW.c_str() ,hatsuonW.c_str() );
	}
}

void cmudic2yomiConvert(const std::string& filename)
{
	FILE * fp = NULL;

	fp = fopen(filename.c_str() , "rb");
	if (!fp)
	{
		fwprintf(stderr,L"can not open %ls file\n" , _A2W(filename).c_str() );
		return ;
	}
	AutoClear ac([&](){ fclose(fp); });
	
	ReadAllForYomi(fp);
}
